version: '3.8'

services:
  # cloudbeaver:
  #   profiles:
  #     - all
  #   image: dbeaver/cloudbeaver:21.3.5 # use this for x86 etc
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.beav.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.beav.tls=true
  #     - traefik.http.routers.beav.tls.certresolver=lets-encrypt
  #     - traefik.port=8978

  dozzle:
    profiles:
      - all

  # note: must set owner of folders with
  #   sudo chown -R 0:0 ../client-mazak/volumes/grafana
  grafana:
    profiles:
      - all
    labels:
      - traefik.enable=true
      - traefik.http.routers.graf.rule=Host(`demo-north.ladder99.com`)
      - traefik.http.routers.graf.tls=true
      - traefik.http.routers.graf.tls.certresolver=lets-encrypt
      - traefik.port=3000

  hue:
    profiles:
      - all

  postgres:
    # command: postgres -c 'max_connections=50' # moved to compose.yaml
    profiles:
      - all

  relay:
    profiles:
      - all
    environment:
      AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717
      #. will need to boost this as number of devices increases,
      # until have automatic rate setting OR use streaming
      # FETCH_INTERVAL: 2000
      # FETCH_COUNT: 800

  traefik:
    profiles:
      - all
