version: '3.8'

services:
  adapter:
    profiles:
      - all

  agent:
    # try out agent2.0
    # image: ladder99/agent2:latest
    profiles:
      - all
    ports:
      - '5000:5000'
    labels:
      - traefik.enable=true
      - traefik.http.routers.agent.rule=Host(`demo-north-agent.ladder99.com`)
      - traefik.http.routers.agent.tls=true
      - traefik.http.routers.agent.tls.certresolver=lets-encrypt
      - traefik.port=5000

  # cloudbeaver:
  #   profiles:
  #     - all
  #   image: dbeaver/cloudbeaver:21.3.5 # use this for x86 etc
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.cloudbeaver.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.cloudbeaver.tls=true
  #     - traefik.http.routers.cloudbeaver.tls.certresolver=lets-encrypt
  #     - traefik.port=8978

  dozzle:
    profiles:
      - all

  # note: must set owner of folders with
  #   sudo chown -R 0:0 ../client-mazak/volumes/grafana
  grafana:
    profiles:
      - all
    #. can you set grafana_port to nothing?
    ports:
      - '$GRAFANA_PORT:3000/tcp'
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`demo-north.ladder99.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
      - traefik.port=3000

  # hue:
  #   profiles:
  #     - all
  #   dns: 8.8.8.8
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.hue.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.hue.tls=true
  #     - traefik.http.routers.hue.tls.certresolver=lets-encrypt
  #     - traefik.port=8888

  pgadmin:
    profiles:
      - all
    dns: 8.8.8.8
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`demo-north-beaver.ladder99.com`)
      - traefik.http.routers.pgadmin.tls=true
      - traefik.http.routers.pgadmin.tls.certresolver=lets-encrypt
      - traefik.port=8888

  postgres:
    profiles:
      - all
    # IMPORTANT: client might need to add this in compose-overrides.yaml
    ports:
      - '$PGPORT:5432/tcp'

  relay:
    profiles:
      - all
    environment:
      # this can be an agent url, a comma-separated (no spaces) list of urls,
      # or a .txt file with a url per line.
      # NO TRAILING SLASHES
      #. make this an array? but this is an envar so must be a string
      #. or could you set this as a yaml array and it would convert to json string?
      # second one is also visible at http://bunker.mriiot.com:5000
      # AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717,http://10.1.10.206:5000
      # AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717,http://10.1.10.145:5000
      # AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717
      # pass through from .env file with null
      AGENT_ENDPOINTS: null
      #
      #. will need to boost this as number of devices increases,
      # until have automatic rate setting OR use streaming
      # FETCH_INTERVAL: 2000
      # FETCH_COUNT: 800

  traefik:
    profiles:
      - prod
