version: '3.8'

services:
  traefik:
    profiles:
      - all

  # note: must set owner of folders with
  # sudo chown -R 0:0 volumes/grafana
  grafana:
    profiles:
      - all
    labels:
      - traefik.enable=true
      - traefik.http.routers.wiki.rule=Host(`demo-north.ladder99.com`)
      - traefik.http.routers.wiki.tls=true
      - traefik.http.routers.wiki.tls.certresolver=lets-encrypt
      - traefik.port=3000
    networks:
      - web
    ports:
      - 3000/tcp

  postgres:
    profiles:
      - all

  relay:
    profiles:
      - all
    environment:
      # AGENT_ENDPOINTS: http://agent:5000
      AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717
      # #. will need to boost this as number of devices increases,
      # # until have automatic rate setting
      # FETCH_INTERVAL: 2000
      # FETCH_COUNT: 800

# note: need to create the web network manually with
#   docker create network web
# (correct?)
networks:
  web:
    name: web
    external: true
