version: '3.8'

services:
  # cloudbeaver:
  #   profiles:
  #     - all
  #   image: dbeaver/cloudbeaver:21.3.5 # use this for x86 etc
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.beav.rule=Host(`demo-north-beaver.ladder99.com`)
  #     - traefik.http.routers.beav.tls=true
  #     - traefik.http.routers.beav.tls.certresolver=lets-encrypt
  #     - traefik.port=8978

  dozzle:
    profiles:
      - all

  # note: must set owner of folders with
  #   sudo chown -R 0:0 ../client-mazak/volumes/grafana
  grafana:
    profiles:
      - all
    # IMPORTANT: might need to turn this on for a client - have to comment it
    # out here because a client might need no ports exposed.
    #. can you do that by setting grafana_port to nothing?
    # we need this turned off, since traefik is gonna use port 80
    # ports:
    #   - $GRAFANA_PORT:3000/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.graf.rule=Host(`demo-north.ladder99.com`)
      - traefik.http.routers.graf.tls=true
      - traefik.http.routers.graf.tls.certresolver=lets-encrypt
      - traefik.port=3000

  hue:
    profiles:
      - all

  postgres:
    # command: postgres -c 'max_connections=50' # moved to compose.yaml
    profiles:
      - all

  relay:
    profiles:
      - all
    environment:
      # this can be an agent url, a comma-separated (no spaces) list of urls,
      # or a .txt file with a url per line.
      # NO TRAILING SLASHES
      #. make this an array? but this is an envar so must be a string
      # second one is also visible at http://bunker.mriiot.com:5000/
      # AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717,http://10.1.10.206:5000
      # AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717,http://10.1.10.145:5000
      AGENT_ENDPOINTS: http://mtconnect.mazakcorp.com:5717
      #. will need to boost this as number of devices increases,
      # until have automatic rate setting OR use streaming
      # FETCH_INTERVAL: 2000
      # FETCH_COUNT: 800

  traefik:
    profiles:
      - all
