[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$r.KpmgN7$8yHaM4GJpJ9QHm2NR6uBl/"
  ]

[http.routers.api]
  rule = "Host(`demo-north-monitor.ladder99.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
